services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - my_network

  backend:
    image: seranise/university-api:latest
    container_name: university-api
    command: gunicorn university_api.wsgi --bind 0.0.0.0:8000
    volumes:
      - static_files:/app/staticfiles
      - ./university_api:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - my_network

  frontend1:
    image: seranise/university-client:latest
    container_name: frontend1
    environment:
      - NODE_ID=frontend1
    ports:
      - "3004:5173"
    depends_on:
      - backend
    networks:
      - my_network

  frontend2:
    image: seranise/university-client:latest
    container_name: frontend2
    environment:
      - NODE_ID=frontend2
    ports:
      - "3005:5173"
    depends_on:
      - backend
    networks:
      - my_network

  frontend3:
    image: seranise/university-client:latest
    container_name: frontend3
    environment:
      - NODE_ID=frontend3
    ports:
      - "3006:5173"
    depends_on:
      - backend
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8082:8080"
    volumes:
      - static_files:/app/staticfiles:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend1
      - frontend2
      - frontend3
      - backend
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    networks:
      - my_network

  celery:
    image: seranise/university-api:latest
    container_name: celery_worker
    command: celery -A university_api.celery worker --loglevel=info
    volumes:
      - ./university_api:/app
    depends_on:
      - redis
      - backend
    networks:
      - my_network

  celery-beat:
    image: seranise/university-api:latest
    container_name: celery_beat
    command: celery -A university_api.celery beat --loglevel=info
    volumes:
      - ./university_api:/app
    depends_on:
      - redis
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  static_files:
