services:
  app:
    build:
      context .
    volumes:
      - .:/core
    ports:
      - 5173:5173
    image: university-client
    container_name: university-client-container
    command: npm run dev -- --host 0.0.0.0