services:
  app:
    image: seranise/university-client:latest
    volumes:
      - .:/client
    ports:
      - 5173:5173
    container_name: university-client-container
    command: npm run dev -- --host 0.0.0.0
